apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-map
  template:
    metadata:
      labels:
        app: memory-map
    spec:
      containers:
        - name: memory-map
          image: ${IMAGE_URL}
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "${DB_URL}"
            - name: DB_USERNAME
              value: "${DB_USERNAME}"
            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"
            - name: CLIENT_ID
              value: "${CLIENT_ID}"
            - name: CLIENT_SECRET
              value: "${CLIENT_SECRET}"
            - name: REDIRECT_URI
              value: "${REDIRECT_URI}"
            - name: JWT_SECRET
              value: "${JWT_SECRET}"
            - name: ACCESS_TOKEN_EXPIRATION_MS
              value: "3600000"
            - name: REFRESH_TOKEN_EXPIRATION_MS
              value: "1209600000"
---
apiVersion: v1
kind: Service
metadata:
  name: memory-map
spec:
  selector:
    app: memory-map
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer